### ISSUE TITLE
Empty Row return

### ISSUE THREAD

**Issue by aconite33** [bitsadmin/wesng#42]
Receiving an error when looking up KB on the Microsoft Update Catalog. If the rows returned is None, you will receive an error:

```
[+] Looking up superseeding hotfixes in the Microsoft Update Catalog
    - Looking up potentially missing KB3197873  [...] found: []
Traceback (most recent call last):
  File "wes.py", line 799, in <module>
    main()
  File "wes.py", line 210, in main
    filtered = apply_muc_filter(filtered, hotfixes_orig)
  File "/root/Downloads/wesng/muc_lookup.py", line 94, in apply_muc_filter
    superseeded_by[kb] = set(lookup_supersedence(kb))
  File "/root/Downloads/wesng/muc_lookup.py", line 119, in lookup_supersedence
    updates = rows.find_all(
AttributeError: 'NoneType' object has no attribute 'find_all'
```

I've made a pull request to fix this: https://github.com/bitsadmin/wesng/pull/41

**Comment by bitsadmin** [comment]
Thanks @aconite33! I merged your fix.
